package org.estudo.theMealDB.model;

public record Meal(String idMeal,
                   String strMeal,
                   String strDrinkAlternate,
                   String strCategory,
                   String strArea,
                   String strInstructions,
                   String strMealThumb,
                   String strTags,
                   String strYoutube,
                   String strIngredient1,
                   String strIngredient2,
                   String strIngredient3,
                   String strIngredient4,
                   String strIngredient5,
                   String strIngredient6,
                   String strIngredient7,
                   String strIngredient8,
                   String strIngredient9,
                   String strIngredient10,
                   String strMeasure1,
                   String strMeasure2,
                   String strMeasure3,
                   String strMeasure4,
                   String strMeasure5,
                   String strMeasure6,
                   String strMeasure7,
                   String strMeasure8,
                   String strMeasure9,
                   String strMeasure10,
                   String strSource,
                   String strImageSource,
                   String strCreativeCommonsConfirmed,
                   String dateModified) {
}
